Added a new Field in FormBuilder to support Radio Groups
SouthbankSoftware/dbkoda-ui pull request #9
Opened 2018-06-27 04:46 UTC by wshamim

2018-06-28 14:17 UTC, michaeljharrison requested changes
Functionally looks good, few minor changes to make before we merge it, I've added comments to the relevant sections but here is an overall:

- Ability to add Tooltips for individual radio elements.
- Swap SimpleQuery Or and And fields to this new radio button component.
- Get styling approved / created by Kalid, if he's happy with it I'm happy with it.

2018-06-28 14:17 UTC, michaeljharrison commented on src/components/TreeActionPanel/FormBuilder.js
> +    if (defField.type == 'Radio') {
Should we be using === here for good practice?

2018-06-28 14:17 UTC, michaeljharrison commented on src/components/AggregateViews/AggregateBlocks/BlockDefinitions/Match.ddd.json
> +          "label": "Use Or?",
Change to "Use $or"

2018-06-28 14:17 UTC, michaeljharrison commented on src/components/AggregateViews/AggregateBlocks/BlockDefinitions/Match.ddd.json
> +          "label": "Use And?",
Change to "Use $and"

2018-06-28 14:17 UTC, michaeljharrison commented on src/components/AggregateViews/AggregateBlocks/BlockDefinitions/Match.ddd.json
> +          "label": "none",
Change to "Default"

2018-07-02 02:43 UTC, wshamim commented
I have incorporated the changes which you have requested. Have a look now and let me know if anything else is required.

2018-07-02 22:07 UTC, michaeljharrison approved these changes
Looks good.

2018-07-02 22:07 UTC, merged